# confirm
confirm_os_window_close 0

# keyconfig
clear_all_shortcuts yes

# colorscheme Elly.vim
color0			#111a1f
background		#111a1f

color1			#8d7856
color9			#8d7856

color2			#798362
color10			#798362

color3			#9b9257
color11			#9b9257

color4			#63768a
color12			#63768a

color5			#738c9c
color13			#738c9c

color6			#6998b3
color14			#6998b3

color7			#acb3b5
color15			#acb3b5

color8			#868b8d

cursor			#9b9257
cursor_text_color	#1e232b
foreground		#acb3b5
url_color		#005bbb
selection_foreground	#2e333c
selection_background	#161f2a

# font
font_family          Cascadia Code Nerd Font Complete
bold_font            auto
italic_font          auto
bold_italick_font    auto
disable_ligatures    never
font_size            15

# opacity
background_opacity   0.9

# window margin
window_margin_width  5
