## escape-time
set -sg escape-time 1

## plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'
# init tmux plugin manager
run '~/.tmux/plugins/tpm/tpm'

## color
set -sa terminal-overrides ',xterm-256color:RGB'

## history
set -g history-limit 100000

## keybinding
# prefix
set -g prefix C-q 
# source
bind r source-file ~/.tmux.conf
# move
bind o select-pane -t :.+
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# size
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5
# split
bind v split-window -h
bind s split-window -v
# clear
bind -n C-l send-keys "clear"\; send-keys "Enter"
# exit
bind C-q kill-session

## pane
## status-bar
# general
set -g status-interval 1
set -g status-position top
set -g status-bg "colour234"
set -g status-fg "colour248"
set -g status-justify "centre"
# status-window-current
set -g window-status-current-format "\
#[fg=colour248]#[bg=colour248]#[fg=colour002]#I#[fg=colour234]:#W[#F]#[default]#[fg=colour248]\
"
# status-left
set -g status-left-length 45 
set -g status-left "\
#[fg=colour101]#[default]\
#[bg=colour101]#[fg=colour234] Session:[#S]#[default]\
#[bg=colour236]#[fg=colour101]#[default]\
#[bg=colour236]#[fg=colour101] Window:[#I]#[default]\
#[bg=colour238]#[fg=colour236]#[default]\
#[bg=colour238]#[fg=colour101] Pane:[#P]#[default]\
#[bg=colour234]#[fg=colour238] #[default]\
"
# status-right
set -g status-right-length 57
set -g status-right "\
#[bg=colour234]#[fg=colour238] #[default]\
#[bg=colour238]#[fg=colour101] CPU:#{cpu_percentage} #[default]\
#[bg=colour238]#[fg=colour236]#[default]\
#[bg=colour236]#[fg=colour101] Mem:#{ram_percentage} #[default]\
#[bg=colour236]#[fg=colour101]#[default]\
#[bg=colour101]#[fg=colour234] %Y/%m/%d(%a) %H:%M #[default]\
#[fg=colour101]#[default]\
"

# tmux-cpu
run ~/.tmux/plugins/tmux-cpu/cpu.tmux
