[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'ulwlu/elly.vim'
hook_add = '''
set termguicolors
colorscheme elly
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'
hook_add = '''
let g:clever_f_smart_case = 1
let g:clever_f_fix_key_direction = 1
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
   \  'separator': { 'left': "\UE0C1\UE0C0\UE0C4", 'right': "\UE0C4\UE0C0\UE0C2" },
   \  'subseparator': { 'left': "\UE0C5\UE0C4\UE0C5", 'right': "\UE0C5\UE0C4\UE0C5" },
   \  }
'''
